### ISSUE TITLE
Can the model be tested on a single frame?

### ISSUE THREAD

**Issue by weibao1001** [Hmslab/Adapose#3]
The above code gives the test of the ITOP data set. I can test my own data in a single frame. How should I test it?

**Comment by Hmslab** [comment]
Since we train our model with motion sequence of 13 frames, the default window_size is set to 13. You can revise the number of "batch_size" and "window_size" in flag.py file to 1 for testing a single image.

**Comment by weibao1001** [comment]
> 




> 由于我们使用 13 帧的运动序列训练模型，因此默认window_size设置为 13。您可以将 flag.py 文件中的“batch_size”和“window_size”的数量修改为 1，以测试单个映像。

thank you
