### ISSUE TITLE
How to test the NTU dataset

### ISSUE THREAD

**Issue by weibao1001** [Hmslab/Adapose#5]
I tested the ITOP dataset, but I can't find the code module for testing the NTU dataset. Do I need to write this test code myself?

**Comment by zqq-judy** [comment]
Hello, have you already written the code about NTU dataset? Is it convenient to share?

**Comment by Hmslab** [comment]
Thanks for your comment！
We have released the configuration file /NTU/flags_NTU.py  and the corresponding data loading code of NTU dataset, the training and testing codes are similar with ITOP.

**Comment by weibao1001** [comment]
> 我们发布了NTU数据集的配置文件/NTU/flags_NTU.py和相应的数据加载代码，训练和测试代码与ITOP类似。

thank you
