### ISSUE TITLE
how to get skeleton in flags.py file?

### ISSUE THREAD

**Issue by zqq-judy** [Hmslab/Adapose#6]
hello, how to get skeleton in flags.py file?
`skeleton = [0.18099216, 0.30136532, 0.3083691, 0.1809909, 0.30517647, 0.3111792, 0.26156965,
            0.4784025, 0.46032718, 0.26156482, 0.47747827, 0.4607155, 0.23529877, 0.23755938]`
I want to generate this skeleton for the NTU dataset.

**Comment by LauSkygh** [comment]
Hello, have you found this skeleton in this NTU dataset?

**Comment by shaqings** [comment]
> hello, how to get skeleton in flags.py file? `skeleton = [0.18099216, 0.30136532, 0.3083691, 0.1809909, 0.30517647, 0.3111792, 0.26156965, 0.4784025, 0.46032718, 0.26156482, 0.47747827, 0.4607155, 0.23529877, 0.23755938]` I want to generate this skeleton for the NTU dataset.
Hello, have you found this skeleton in this NTU dataset?
